import * as AccountAccount from './AccountAccount.json';
import * as AccountAccountsList from './AccountAccountsList.json';
import * as AccountCanIResponse from './AccountCanIResponse.json';
import * as AccountCreateTokenRequest from './AccountCreateTokenRequest.json';
import * as AccountCreateTokenResponse from './AccountCreateTokenResponse.json';
import * as AccountToken from './AccountToken.json';
import * as AccountUpdatePasswordRequest from './AccountUpdatePasswordRequest.json';
import * as ApplicationApplicationManifestQueryWithFiles from './ApplicationApplicationManifestQueryWithFiles.json';
import * as ApplicationApplicationManifestQueryWithFilesWrapper from './ApplicationApplicationManifestQueryWithFilesWrapper.json';
import * as ApplicationApplicationPatchRequest from './ApplicationApplicationPatchRequest.json';
import * as ApplicationApplicationResourceResponse from './ApplicationApplicationResourceResponse.json';
import * as ApplicationApplicationRollbackRequest from './ApplicationApplicationRollbackRequest.json';
import * as ApplicationApplicationSyncRequest from './ApplicationApplicationSyncRequest.json';
import * as ApplicationApplicationSyncWindow from './ApplicationApplicationSyncWindow.json';
import * as ApplicationApplicationSyncWindowsResponse from './ApplicationApplicationSyncWindowsResponse.json';
import * as ApplicationFileChunk from './ApplicationFileChunk.json';
import * as ApplicationLinkInfo from './ApplicationLinkInfo.json';
import * as ApplicationLinksResponse from './ApplicationLinksResponse.json';
import * as ApplicationLogEntry from './ApplicationLogEntry.json';
import * as ApplicationManagedResourcesResponse from './ApplicationManagedResourcesResponse.json';
import * as ApplicationResourceActionsListResponse from './ApplicationResourceActionsListResponse.json';
import * as ApplicationSyncOptions from './ApplicationSyncOptions.json';
import * as ApplicationsetApplicationSetResponse from './ApplicationsetApplicationSetResponse.json';
import * as Applicationv1alpha1EnvEntry from './Applicationv1alpha1EnvEntry.json';
import * as ClusterClusterID from './ClusterClusterID.json';
import * as ClusterConnector from './ClusterConnector.json';
import * as ClusterDexConfig from './ClusterDexConfig.json';
import * as ClusterGoogleAnalyticsConfig from './ClusterGoogleAnalyticsConfig.json';
import * as ClusterHelp from './ClusterHelp.json';
import * as ClusterOIDCConfig from './ClusterOIDCConfig.json';
import * as ClusterPlugin from './ClusterPlugin.json';
import * as ClusterSettings from './ClusterSettings.json';
import * as ClusterSettingsPluginsResponse from './ClusterSettingsPluginsResponse.json';
import * as GpgkeyGnuPGPublicKeyCreateResponse from './GpgkeyGnuPGPublicKeyCreateResponse.json';
import * as IntstrIntOrString from './IntstrIntOrString.json';
import * as NotificationService from './NotificationService.json';
import * as NotificationServiceList from './NotificationServiceList.json';
import * as NotificationTemplate from './NotificationTemplate.json';
import * as NotificationTemplateList from './NotificationTemplateList.json';
import * as NotificationTrigger from './NotificationTrigger.json';
import * as NotificationTriggerList from './NotificationTriggerList.json';
import * as OidcClaim from './OidcClaim.json';
import * as ProjectDetailedProjectsResponse from './ProjectDetailedProjectsResponse.json';
import * as ProjectGlobalProjectsResponse from './ProjectGlobalProjectsResponse.json';
import * as ProjectProjectCreateRequest from './ProjectProjectCreateRequest.json';
import * as ProjectProjectTokenCreateRequest from './ProjectProjectTokenCreateRequest.json';
import * as ProjectProjectTokenResponse from './ProjectProjectTokenResponse.json';
import * as ProjectProjectUpdateRequest from './ProjectProjectUpdateRequest.json';
import * as ProjectSyncWindowsResponse from './ProjectSyncWindowsResponse.json';
import * as ProtobufAny from './ProtobufAny.json';
import * as RepositoryAppInfo from './RepositoryAppInfo.json';
import * as RepositoryHelmAppSpec from './RepositoryHelmAppSpec.json';
import * as RepositoryHelmChart from './RepositoryHelmChart.json';
import * as RepositoryHelmChartsResponse from './RepositoryHelmChartsResponse.json';
import * as RepositoryKustomizeAppSpec from './RepositoryKustomizeAppSpec.json';
import * as RepositoryManifestResponse from './RepositoryManifestResponse.json';
import * as RepositoryParameterAnnouncement from './RepositoryParameterAnnouncement.json';
import * as RepositoryPluginAppSpec from './RepositoryPluginAppSpec.json';
import * as RepositoryRefs from './RepositoryRefs.json';
import * as RepositoryRepoAppDetailsQuery from './RepositoryRepoAppDetailsQuery.json';
import * as RepositoryRepoAppDetailsResponse from './RepositoryRepoAppDetailsResponse.json';
import * as RepositoryRepoAppsResponse from './RepositoryRepoAppsResponse.json';
import * as RuntimeError from './RuntimeError.json';
import * as RuntimeRawExtension from './RuntimeRawExtension.json';
import * as RuntimeStreamError from './RuntimeStreamError.json';
import * as SessionGetUserInfoResponse from './SessionGetUserInfoResponse.json';
import * as SessionSessionCreateRequest from './SessionSessionCreateRequest.json';
import * as SessionSessionResponse from './SessionSessionResponse.json';
import * as StreamResultOfApplicationLogEntry from './StreamResultOfApplicationLogEntry.json';
import * as StreamResultOfV1alpha1ApplicationTree from './StreamResultOfV1alpha1ApplicationTree.json';
import * as StreamResultOfV1alpha1ApplicationWatchEvent from './StreamResultOfV1alpha1ApplicationWatchEvent.json';
import * as V1Event from './V1Event.json';
import * as V1EventList from './V1EventList.json';
import * as V1EventSeries from './V1EventSeries.json';
import * as V1EventSource from './V1EventSource.json';
import * as V1FieldsV1 from './V1FieldsV1.json';
import * as V1GroupKind from './V1GroupKind.json';
import * as V1JSON from './V1JSON.json';
import * as V1LabelSelector from './V1LabelSelector.json';
import * as V1LabelSelectorRequirement from './V1LabelSelectorRequirement.json';
import * as V1ListMeta from './V1ListMeta.json';
import * as V1LoadBalancerIngress from './V1LoadBalancerIngress.json';
import * as V1ManagedFieldsEntry from './V1ManagedFieldsEntry.json';
import * as V1MicroTime from './V1MicroTime.json';
import * as V1NodeSystemInfo from './V1NodeSystemInfo.json';
import * as V1ObjectMeta from './V1ObjectMeta.json';
import * as V1ObjectReference from './V1ObjectReference.json';
import * as V1OwnerReference from './V1OwnerReference.json';
import * as V1PortStatus from './V1PortStatus.json';
import * as V1alpha1AWSAuthConfig from './V1alpha1AWSAuthConfig.json';
import * as V1alpha1AppProject from './V1alpha1AppProject.json';
import * as V1alpha1AppProjectList from './V1alpha1AppProjectList.json';
import * as V1alpha1AppProjectSpec from './V1alpha1AppProjectSpec.json';
import * as V1alpha1AppProjectStatus from './V1alpha1AppProjectStatus.json';
import * as V1alpha1Application from './V1alpha1Application.json';
import * as V1alpha1ApplicationCondition from './V1alpha1ApplicationCondition.json';
import * as V1alpha1ApplicationDestination from './V1alpha1ApplicationDestination.json';
import * as V1alpha1ApplicationList from './V1alpha1ApplicationList.json';
import * as V1alpha1ApplicationMatchExpression from './V1alpha1ApplicationMatchExpression.json';
import * as V1alpha1ApplicationPreservedFields from './V1alpha1ApplicationPreservedFields.json';
import * as V1alpha1ApplicationSet from './V1alpha1ApplicationSet.json';
import * as V1alpha1ApplicationSetApplicationStatus from './V1alpha1ApplicationSetApplicationStatus.json';
import * as V1alpha1ApplicationSetCondition from './V1alpha1ApplicationSetCondition.json';
import * as V1alpha1ApplicationSetGenerator from './V1alpha1ApplicationSetGenerator.json';
import * as V1alpha1ApplicationSetList from './V1alpha1ApplicationSetList.json';
import * as V1alpha1ApplicationSetNestedGenerator from './V1alpha1ApplicationSetNestedGenerator.json';
import * as V1alpha1ApplicationSetRolloutStep from './V1alpha1ApplicationSetRolloutStep.json';
import * as V1alpha1ApplicationSetRolloutStrategy from './V1alpha1ApplicationSetRolloutStrategy.json';
import * as V1alpha1ApplicationSetSpec from './V1alpha1ApplicationSetSpec.json';
import * as V1alpha1ApplicationSetStatus from './V1alpha1ApplicationSetStatus.json';
import * as V1alpha1ApplicationSetStrategy from './V1alpha1ApplicationSetStrategy.json';
import * as V1alpha1ApplicationSetSyncPolicy from './V1alpha1ApplicationSetSyncPolicy.json';
import * as V1alpha1ApplicationSetTemplate from './V1alpha1ApplicationSetTemplate.json';
import * as V1alpha1ApplicationSetTemplateMeta from './V1alpha1ApplicationSetTemplateMeta.json';
import * as V1alpha1ApplicationSource from './V1alpha1ApplicationSource.json';
import * as V1alpha1ApplicationSourceDirectory from './V1alpha1ApplicationSourceDirectory.json';
import * as V1alpha1ApplicationSourceHelm from './V1alpha1ApplicationSourceHelm.json';
import * as V1alpha1ApplicationSourceJsonnet from './V1alpha1ApplicationSourceJsonnet.json';
import * as V1alpha1ApplicationSourceKustomize from './V1alpha1ApplicationSourceKustomize.json';
import * as V1alpha1ApplicationSourcePlugin from './V1alpha1ApplicationSourcePlugin.json';
import * as V1alpha1ApplicationSourcePluginParameter from './V1alpha1ApplicationSourcePluginParameter.json';
import * as V1alpha1ApplicationSpec from './V1alpha1ApplicationSpec.json';
import * as V1alpha1ApplicationStatus from './V1alpha1ApplicationStatus.json';
import * as V1alpha1ApplicationSummary from './V1alpha1ApplicationSummary.json';
import * as V1alpha1ApplicationTree from './V1alpha1ApplicationTree.json';
import * as V1alpha1ApplicationWatchEvent from './V1alpha1ApplicationWatchEvent.json';
import * as V1alpha1Backoff from './V1alpha1Backoff.json';
import * as V1alpha1BasicAuthBitbucketServer from './V1alpha1BasicAuthBitbucketServer.json';
import * as V1alpha1BearerTokenBitbucketCloud from './V1alpha1BearerTokenBitbucketCloud.json';
import * as V1alpha1ChartDetails from './V1alpha1ChartDetails.json';
import * as V1alpha1Cluster from './V1alpha1Cluster.json';
import * as V1alpha1ClusterCacheInfo from './V1alpha1ClusterCacheInfo.json';
import * as V1alpha1ClusterConfig from './V1alpha1ClusterConfig.json';
import * as V1alpha1ClusterGenerator from './V1alpha1ClusterGenerator.json';
import * as V1alpha1ClusterInfo from './V1alpha1ClusterInfo.json';
import * as V1alpha1ClusterList from './V1alpha1ClusterList.json';
import * as V1alpha1Command from './V1alpha1Command.json';
import * as V1alpha1ComparedTo from './V1alpha1ComparedTo.json';
import * as V1alpha1ConfigManagementPlugin from './V1alpha1ConfigManagementPlugin.json';
import * as V1alpha1ConnectionState from './V1alpha1ConnectionState.json';
import * as V1alpha1DuckTypeGenerator from './V1alpha1DuckTypeGenerator.json';
import * as V1alpha1ExecProviderConfig from './V1alpha1ExecProviderConfig.json';
import * as V1alpha1GitDirectoryGeneratorItem from './V1alpha1GitDirectoryGeneratorItem.json';
import * as V1alpha1GitFileGeneratorItem from './V1alpha1GitFileGeneratorItem.json';
import * as V1alpha1GitGenerator from './V1alpha1GitGenerator.json';
import * as V1alpha1GnuPGPublicKey from './V1alpha1GnuPGPublicKey.json';
import * as V1alpha1GnuPGPublicKeyList from './V1alpha1GnuPGPublicKeyList.json';
import * as V1alpha1HealthStatus from './V1alpha1HealthStatus.json';
import * as V1alpha1HelmFileParameter from './V1alpha1HelmFileParameter.json';
import * as V1alpha1HelmParameter from './V1alpha1HelmParameter.json';
import * as V1alpha1HostInfo from './V1alpha1HostInfo.json';
import * as V1alpha1HostResourceInfo from './V1alpha1HostResourceInfo.json';
import * as V1alpha1Info from './V1alpha1Info.json';
import * as V1alpha1InfoItem from './V1alpha1InfoItem.json';
import * as V1alpha1JWTToken from './V1alpha1JWTToken.json';
import * as V1alpha1JWTTokens from './V1alpha1JWTTokens.json';
import * as V1alpha1JsonnetVar from './V1alpha1JsonnetVar.json';
import * as V1alpha1KnownTypeField from './V1alpha1KnownTypeField.json';
import * as V1alpha1KustomizeOptions from './V1alpha1KustomizeOptions.json';
import * as V1alpha1KustomizeReplica from './V1alpha1KustomizeReplica.json';
import * as V1alpha1ListGenerator from './V1alpha1ListGenerator.json';
import * as V1alpha1ManagedNamespaceMetadata from './V1alpha1ManagedNamespaceMetadata.json';
import * as V1alpha1MatrixGenerator from './V1alpha1MatrixGenerator.json';
import * as V1alpha1MergeGenerator from './V1alpha1MergeGenerator.json';
import * as V1alpha1Operation from './V1alpha1Operation.json';
import * as V1alpha1OperationInitiator from './V1alpha1OperationInitiator.json';
import * as V1alpha1OperationState from './V1alpha1OperationState.json';
import * as V1alpha1OrphanedResourceKey from './V1alpha1OrphanedResourceKey.json';
import * as V1alpha1OrphanedResourcesMonitorSettings from './V1alpha1OrphanedResourcesMonitorSettings.json';
import * as V1alpha1OverrideIgnoreDiff from './V1alpha1OverrideIgnoreDiff.json';
import * as V1alpha1PluginConfigMapRef from './V1alpha1PluginConfigMapRef.json';
import * as V1alpha1PluginGenerator from './V1alpha1PluginGenerator.json';
import * as V1alpha1PluginInput from './V1alpha1PluginInput.json';
import * as V1alpha1ProjectRole from './V1alpha1ProjectRole.json';
import * as V1alpha1PullRequestGenerator from './V1alpha1PullRequestGenerator.json';
import * as V1alpha1PullRequestGeneratorAzureDevOps from './V1alpha1PullRequestGeneratorAzureDevOps.json';
import * as V1alpha1PullRequestGeneratorBitbucket from './V1alpha1PullRequestGeneratorBitbucket.json';
import * as V1alpha1PullRequestGeneratorBitbucketServer from './V1alpha1PullRequestGeneratorBitbucketServer.json';
import * as V1alpha1PullRequestGeneratorFilter from './V1alpha1PullRequestGeneratorFilter.json';
import * as V1alpha1PullRequestGeneratorGitLab from './V1alpha1PullRequestGeneratorGitLab.json';
import * as V1alpha1PullRequestGeneratorGitea from './V1alpha1PullRequestGeneratorGitea.json';
import * as V1alpha1PullRequestGeneratorGithub from './V1alpha1PullRequestGeneratorGithub.json';
import * as V1alpha1RepoCreds from './V1alpha1RepoCreds.json';
import * as V1alpha1RepoCredsList from './V1alpha1RepoCredsList.json';
import * as V1alpha1Repository from './V1alpha1Repository.json';
import * as V1alpha1RepositoryCertificate from './V1alpha1RepositoryCertificate.json';
import * as V1alpha1RepositoryCertificateList from './V1alpha1RepositoryCertificateList.json';
import * as V1alpha1RepositoryList from './V1alpha1RepositoryList.json';
import * as V1alpha1ResourceAction from './V1alpha1ResourceAction.json';
import * as V1alpha1ResourceActionParam from './V1alpha1ResourceActionParam.json';
import * as V1alpha1ResourceDiff from './V1alpha1ResourceDiff.json';
import * as V1alpha1ResourceIgnoreDifferences from './V1alpha1ResourceIgnoreDifferences.json';
import * as V1alpha1ResourceNetworkingInfo from './V1alpha1ResourceNetworkingInfo.json';
import * as V1alpha1ResourceNode from './V1alpha1ResourceNode.json';
import * as V1alpha1ResourceOverride from './V1alpha1ResourceOverride.json';
import * as V1alpha1ResourceRef from './V1alpha1ResourceRef.json';
import * as V1alpha1ResourceResult from './V1alpha1ResourceResult.json';
import * as V1alpha1ResourceStatus from './V1alpha1ResourceStatus.json';
import * as V1alpha1RetryStrategy from './V1alpha1RetryStrategy.json';
import * as V1alpha1RevisionHistory from './V1alpha1RevisionHistory.json';
import * as V1alpha1RevisionMetadata from './V1alpha1RevisionMetadata.json';
import * as V1alpha1SCMProviderGenerator from './V1alpha1SCMProviderGenerator.json';
import * as V1alpha1SCMProviderGeneratorAWSCodeCommit from './V1alpha1SCMProviderGeneratorAWSCodeCommit.json';
import * as V1alpha1SCMProviderGeneratorAzureDevOps from './V1alpha1SCMProviderGeneratorAzureDevOps.json';
import * as V1alpha1SCMProviderGeneratorBitbucket from './V1alpha1SCMProviderGeneratorBitbucket.json';
import * as V1alpha1SCMProviderGeneratorBitbucketServer from './V1alpha1SCMProviderGeneratorBitbucketServer.json';
import * as V1alpha1SCMProviderGeneratorFilter from './V1alpha1SCMProviderGeneratorFilter.json';
import * as V1alpha1SCMProviderGeneratorGitea from './V1alpha1SCMProviderGeneratorGitea.json';
import * as V1alpha1SCMProviderGeneratorGithub from './V1alpha1SCMProviderGeneratorGithub.json';
import * as V1alpha1SCMProviderGeneratorGitlab from './V1alpha1SCMProviderGeneratorGitlab.json';
import * as V1alpha1SecretRef from './V1alpha1SecretRef.json';
import * as V1alpha1SignatureKey from './V1alpha1SignatureKey.json';
import * as V1alpha1SyncOperation from './V1alpha1SyncOperation.json';
import * as V1alpha1SyncOperationResource from './V1alpha1SyncOperationResource.json';
import * as V1alpha1SyncOperationResult from './V1alpha1SyncOperationResult.json';
import * as V1alpha1SyncPolicy from './V1alpha1SyncPolicy.json';
import * as V1alpha1SyncPolicyAutomated from './V1alpha1SyncPolicyAutomated.json';
import * as V1alpha1SyncStatus from './V1alpha1SyncStatus.json';
import * as V1alpha1SyncStrategy from './V1alpha1SyncStrategy.json';
import * as V1alpha1SyncStrategyApply from './V1alpha1SyncStrategyApply.json';
import * as V1alpha1SyncStrategyHook from './V1alpha1SyncStrategyHook.json';
import * as V1alpha1SyncWindow from './V1alpha1SyncWindow.json';
import * as V1alpha1TLSClientConfig from './V1alpha1TLSClientConfig.json';
import * as V1alpha1TagFilter from './V1alpha1TagFilter.json';
import * as VersionVersionMessage from './VersionVersionMessage.json';

export const AccountAccountSchema = AccountAccount;
export const AccountAccountsListSchema = AccountAccountsList;
export const AccountCanIResponseSchema = AccountCanIResponse;
export const AccountCreateTokenRequestSchema = AccountCreateTokenRequest;
export const AccountCreateTokenResponseSchema = AccountCreateTokenResponse;
export const AccountTokenSchema = AccountToken;
export const AccountUpdatePasswordRequestSchema = AccountUpdatePasswordRequest;
export const ApplicationApplicationManifestQueryWithFilesSchema = ApplicationApplicationManifestQueryWithFiles;
export const ApplicationApplicationManifestQueryWithFilesWrapperSchema =
  ApplicationApplicationManifestQueryWithFilesWrapper;
export const ApplicationApplicationPatchRequestSchema = ApplicationApplicationPatchRequest;
export const ApplicationApplicationResourceResponseSchema = ApplicationApplicationResourceResponse;
export const ApplicationApplicationRollbackRequestSchema = ApplicationApplicationRollbackRequest;
export const ApplicationApplicationSyncRequestSchema = ApplicationApplicationSyncRequest;
export const ApplicationApplicationSyncWindowSchema = ApplicationApplicationSyncWindow;
export const ApplicationApplicationSyncWindowsResponseSchema = ApplicationApplicationSyncWindowsResponse;
export const ApplicationFileChunkSchema = ApplicationFileChunk;
export const ApplicationLinkInfoSchema = ApplicationLinkInfo;
export const ApplicationLinksResponseSchema = ApplicationLinksResponse;
export const ApplicationLogEntrySchema = ApplicationLogEntry;
export const ApplicationManagedResourcesResponseSchema = ApplicationManagedResourcesResponse;
export const ApplicationResourceActionsListResponseSchema = ApplicationResourceActionsListResponse;
export const ApplicationSyncOptionsSchema = ApplicationSyncOptions;
export const ApplicationsetApplicationSetResponseSchema = ApplicationsetApplicationSetResponse;
export const Applicationv1alpha1EnvEntrySchema = Applicationv1alpha1EnvEntry;
export const ClusterClusterIDSchema = ClusterClusterID;
export const ClusterConnectorSchema = ClusterConnector;
export const ClusterDexConfigSchema = ClusterDexConfig;
export const ClusterGoogleAnalyticsConfigSchema = ClusterGoogleAnalyticsConfig;
export const ClusterHelpSchema = ClusterHelp;
export const ClusterOIDCConfigSchema = ClusterOIDCConfig;
export const ClusterPluginSchema = ClusterPlugin;
export const ClusterSettingsSchema = ClusterSettings;
export const ClusterSettingsPluginsResponseSchema = ClusterSettingsPluginsResponse;
export const GpgkeyGnuPGPublicKeyCreateResponseSchema = GpgkeyGnuPGPublicKeyCreateResponse;
export const IntstrIntOrStringSchema = IntstrIntOrString;
export const NotificationServiceSchema = NotificationService;
export const NotificationServiceListSchema = NotificationServiceList;
export const NotificationTemplateSchema = NotificationTemplate;
export const NotificationTemplateListSchema = NotificationTemplateList;
export const NotificationTriggerSchema = NotificationTrigger;
export const NotificationTriggerListSchema = NotificationTriggerList;
export const OidcClaimSchema = OidcClaim;
export const ProjectDetailedProjectsResponseSchema = ProjectDetailedProjectsResponse;
export const ProjectGlobalProjectsResponseSchema = ProjectGlobalProjectsResponse;
export const ProjectProjectCreateRequestSchema = ProjectProjectCreateRequest;
export const ProjectProjectTokenCreateRequestSchema = ProjectProjectTokenCreateRequest;
export const ProjectProjectTokenResponseSchema = ProjectProjectTokenResponse;
export const ProjectProjectUpdateRequestSchema = ProjectProjectUpdateRequest;
export const ProjectSyncWindowsResponseSchema = ProjectSyncWindowsResponse;
export const ProtobufAnySchema = ProtobufAny;
export const RepositoryAppInfoSchema = RepositoryAppInfo;
export const RepositoryHelmAppSpecSchema = RepositoryHelmAppSpec;
export const RepositoryHelmChartSchema = RepositoryHelmChart;
export const RepositoryHelmChartsResponseSchema = RepositoryHelmChartsResponse;
export const RepositoryKustomizeAppSpecSchema = RepositoryKustomizeAppSpec;
export const RepositoryManifestResponseSchema = RepositoryManifestResponse;
export const RepositoryParameterAnnouncementSchema = RepositoryParameterAnnouncement;
export const RepositoryPluginAppSpecSchema = RepositoryPluginAppSpec;
export const RepositoryRefsSchema = RepositoryRefs;
export const RepositoryRepoAppDetailsQuerySchema = RepositoryRepoAppDetailsQuery;
export const RepositoryRepoAppDetailsResponseSchema = RepositoryRepoAppDetailsResponse;
export const RepositoryRepoAppsResponseSchema = RepositoryRepoAppsResponse;
export const RuntimeErrorSchema = RuntimeError;
export const RuntimeRawExtensionSchema = RuntimeRawExtension;
export const RuntimeStreamErrorSchema = RuntimeStreamError;
export const SessionGetUserInfoResponseSchema = SessionGetUserInfoResponse;
export const SessionSessionCreateRequestSchema = SessionSessionCreateRequest;
export const SessionSessionResponseSchema = SessionSessionResponse;
export const StreamResultOfApplicationLogEntrySchema = StreamResultOfApplicationLogEntry;
export const StreamResultOfV1alpha1ApplicationTreeSchema = StreamResultOfV1alpha1ApplicationTree;
export const StreamResultOfV1alpha1ApplicationWatchEventSchema = StreamResultOfV1alpha1ApplicationWatchEvent;
export const V1EventSchema = V1Event;
export const V1EventListSchema = V1EventList;
export const V1EventSeriesSchema = V1EventSeries;
export const V1EventSourceSchema = V1EventSource;
export const V1FieldsV1Schema = V1FieldsV1;
export const V1GroupKindSchema = V1GroupKind;
export const V1JSONSchema = V1JSON;
export const V1LabelSelectorSchema = V1LabelSelector;
export const V1LabelSelectorRequirementSchema = V1LabelSelectorRequirement;
export const V1ListMetaSchema = V1ListMeta;
export const V1LoadBalancerIngressSchema = V1LoadBalancerIngress;
export const V1ManagedFieldsEntrySchema = V1ManagedFieldsEntry;
export const V1MicroTimeSchema = V1MicroTime;
export const V1NodeSystemInfoSchema = V1NodeSystemInfo;
export const V1ObjectMetaSchema = V1ObjectMeta;
export const V1ObjectReferenceSchema = V1ObjectReference;
export const V1OwnerReferenceSchema = V1OwnerReference;
export const V1PortStatusSchema = V1PortStatus;
export const V1alpha1AWSAuthConfigSchema = V1alpha1AWSAuthConfig;
export const V1alpha1AppProjectSchema = V1alpha1AppProject;
export const V1alpha1AppProjectListSchema = V1alpha1AppProjectList;
export const V1alpha1AppProjectSpecSchema = V1alpha1AppProjectSpec;
export const V1alpha1AppProjectStatusSchema = V1alpha1AppProjectStatus;
export const V1alpha1ApplicationSchema = V1alpha1Application;
export const V1alpha1ApplicationConditionSchema = V1alpha1ApplicationCondition;
export const V1alpha1ApplicationDestinationSchema = V1alpha1ApplicationDestination;
export const V1alpha1ApplicationListSchema = V1alpha1ApplicationList;
export const V1alpha1ApplicationMatchExpressionSchema = V1alpha1ApplicationMatchExpression;
export const V1alpha1ApplicationPreservedFieldsSchema = V1alpha1ApplicationPreservedFields;
export const V1alpha1ApplicationSetSchema = V1alpha1ApplicationSet;
export const V1alpha1ApplicationSetApplicationStatusSchema = V1alpha1ApplicationSetApplicationStatus;
export const V1alpha1ApplicationSetConditionSchema = V1alpha1ApplicationSetCondition;
export const V1alpha1ApplicationSetGeneratorSchema = V1alpha1ApplicationSetGenerator;
export const V1alpha1ApplicationSetListSchema = V1alpha1ApplicationSetList;
export const V1alpha1ApplicationSetNestedGeneratorSchema = V1alpha1ApplicationSetNestedGenerator;
export const V1alpha1ApplicationSetRolloutStepSchema = V1alpha1ApplicationSetRolloutStep;
export const V1alpha1ApplicationSetRolloutStrategySchema = V1alpha1ApplicationSetRolloutStrategy;
export const V1alpha1ApplicationSetSpecSchema = V1alpha1ApplicationSetSpec;
export const V1alpha1ApplicationSetStatusSchema = V1alpha1ApplicationSetStatus;
export const V1alpha1ApplicationSetStrategySchema = V1alpha1ApplicationSetStrategy;
export const V1alpha1ApplicationSetSyncPolicySchema = V1alpha1ApplicationSetSyncPolicy;
export const V1alpha1ApplicationSetTemplateSchema = V1alpha1ApplicationSetTemplate;
export const V1alpha1ApplicationSetTemplateMetaSchema = V1alpha1ApplicationSetTemplateMeta;
export const V1alpha1ApplicationSourceSchema = V1alpha1ApplicationSource;
export const V1alpha1ApplicationSourceDirectorySchema = V1alpha1ApplicationSourceDirectory;
export const V1alpha1ApplicationSourceHelmSchema = V1alpha1ApplicationSourceHelm;
export const V1alpha1ApplicationSourceJsonnetSchema = V1alpha1ApplicationSourceJsonnet;
export const V1alpha1ApplicationSourceKustomizeSchema = V1alpha1ApplicationSourceKustomize;
export const V1alpha1ApplicationSourcePluginSchema = V1alpha1ApplicationSourcePlugin;
export const V1alpha1ApplicationSourcePluginParameterSchema = V1alpha1ApplicationSourcePluginParameter;
export const V1alpha1ApplicationSpecSchema = V1alpha1ApplicationSpec;
export const V1alpha1ApplicationStatusSchema = V1alpha1ApplicationStatus;
export const V1alpha1ApplicationSummarySchema = V1alpha1ApplicationSummary;
export const V1alpha1ApplicationTreeSchema = V1alpha1ApplicationTree;
export const V1alpha1ApplicationWatchEventSchema = V1alpha1ApplicationWatchEvent;
export const V1alpha1BackoffSchema = V1alpha1Backoff;
export const V1alpha1BasicAuthBitbucketServerSchema = V1alpha1BasicAuthBitbucketServer;
export const V1alpha1BearerTokenBitbucketCloudSchema = V1alpha1BearerTokenBitbucketCloud;
export const V1alpha1ChartDetailsSchema = V1alpha1ChartDetails;
export const V1alpha1ClusterSchema = V1alpha1Cluster;
export const V1alpha1ClusterCacheInfoSchema = V1alpha1ClusterCacheInfo;
export const V1alpha1ClusterConfigSchema = V1alpha1ClusterConfig;
export const V1alpha1ClusterGeneratorSchema = V1alpha1ClusterGenerator;
export const V1alpha1ClusterInfoSchema = V1alpha1ClusterInfo;
export const V1alpha1ClusterListSchema = V1alpha1ClusterList;
export const V1alpha1CommandSchema = V1alpha1Command;
export const V1alpha1ComparedToSchema = V1alpha1ComparedTo;
export const V1alpha1ConfigManagementPluginSchema = V1alpha1ConfigManagementPlugin;
export const V1alpha1ConnectionStateSchema = V1alpha1ConnectionState;
export const V1alpha1DuckTypeGeneratorSchema = V1alpha1DuckTypeGenerator;
export const V1alpha1ExecProviderConfigSchema = V1alpha1ExecProviderConfig;
export const V1alpha1GitDirectoryGeneratorItemSchema = V1alpha1GitDirectoryGeneratorItem;
export const V1alpha1GitFileGeneratorItemSchema = V1alpha1GitFileGeneratorItem;
export const V1alpha1GitGeneratorSchema = V1alpha1GitGenerator;
export const V1alpha1GnuPGPublicKeySchema = V1alpha1GnuPGPublicKey;
export const V1alpha1GnuPGPublicKeyListSchema = V1alpha1GnuPGPublicKeyList;
export const V1alpha1HealthStatusSchema = V1alpha1HealthStatus;
export const V1alpha1HelmFileParameterSchema = V1alpha1HelmFileParameter;
export const V1alpha1HelmParameterSchema = V1alpha1HelmParameter;
export const V1alpha1HostInfoSchema = V1alpha1HostInfo;
export const V1alpha1HostResourceInfoSchema = V1alpha1HostResourceInfo;
export const V1alpha1InfoSchema = V1alpha1Info;
export const V1alpha1InfoItemSchema = V1alpha1InfoItem;
export const V1alpha1JWTTokenSchema = V1alpha1JWTToken;
export const V1alpha1JWTTokensSchema = V1alpha1JWTTokens;
export const V1alpha1JsonnetVarSchema = V1alpha1JsonnetVar;
export const V1alpha1KnownTypeFieldSchema = V1alpha1KnownTypeField;
export const V1alpha1KustomizeOptionsSchema = V1alpha1KustomizeOptions;
export const V1alpha1KustomizeReplicaSchema = V1alpha1KustomizeReplica;
export const V1alpha1ListGeneratorSchema = V1alpha1ListGenerator;
export const V1alpha1ManagedNamespaceMetadataSchema = V1alpha1ManagedNamespaceMetadata;
export const V1alpha1MatrixGeneratorSchema = V1alpha1MatrixGenerator;
export const V1alpha1MergeGeneratorSchema = V1alpha1MergeGenerator;
export const V1alpha1OperationSchema = V1alpha1Operation;
export const V1alpha1OperationInitiatorSchema = V1alpha1OperationInitiator;
export const V1alpha1OperationStateSchema = V1alpha1OperationState;
export const V1alpha1OrphanedResourceKeySchema = V1alpha1OrphanedResourceKey;
export const V1alpha1OrphanedResourcesMonitorSettingsSchema = V1alpha1OrphanedResourcesMonitorSettings;
export const V1alpha1OverrideIgnoreDiffSchema = V1alpha1OverrideIgnoreDiff;
export const V1alpha1PluginConfigMapRefSchema = V1alpha1PluginConfigMapRef;
export const V1alpha1PluginGeneratorSchema = V1alpha1PluginGenerator;
export const V1alpha1PluginInputSchema = V1alpha1PluginInput;
export const V1alpha1ProjectRoleSchema = V1alpha1ProjectRole;
export const V1alpha1PullRequestGeneratorSchema = V1alpha1PullRequestGenerator;
export const V1alpha1PullRequestGeneratorAzureDevOpsSchema = V1alpha1PullRequestGeneratorAzureDevOps;
export const V1alpha1PullRequestGeneratorBitbucketSchema = V1alpha1PullRequestGeneratorBitbucket;
export const V1alpha1PullRequestGeneratorBitbucketServerSchema = V1alpha1PullRequestGeneratorBitbucketServer;
export const V1alpha1PullRequestGeneratorFilterSchema = V1alpha1PullRequestGeneratorFilter;
export const V1alpha1PullRequestGeneratorGitLabSchema = V1alpha1PullRequestGeneratorGitLab;
export const V1alpha1PullRequestGeneratorGiteaSchema = V1alpha1PullRequestGeneratorGitea;
export const V1alpha1PullRequestGeneratorGithubSchema = V1alpha1PullRequestGeneratorGithub;
export const V1alpha1RepoCredsSchema = V1alpha1RepoCreds;
export const V1alpha1RepoCredsListSchema = V1alpha1RepoCredsList;
export const V1alpha1RepositorySchema = V1alpha1Repository;
export const V1alpha1RepositoryCertificateSchema = V1alpha1RepositoryCertificate;
export const V1alpha1RepositoryCertificateListSchema = V1alpha1RepositoryCertificateList;
export const V1alpha1RepositoryListSchema = V1alpha1RepositoryList;
export const V1alpha1ResourceActionSchema = V1alpha1ResourceAction;
export const V1alpha1ResourceActionParamSchema = V1alpha1ResourceActionParam;
export const V1alpha1ResourceDiffSchema = V1alpha1ResourceDiff;
export const V1alpha1ResourceIgnoreDifferencesSchema = V1alpha1ResourceIgnoreDifferences;
export const V1alpha1ResourceNetworkingInfoSchema = V1alpha1ResourceNetworkingInfo;
export const V1alpha1ResourceNodeSchema = V1alpha1ResourceNode;
export const V1alpha1ResourceOverrideSchema = V1alpha1ResourceOverride;
export const V1alpha1ResourceRefSchema = V1alpha1ResourceRef;
export const V1alpha1ResourceResultSchema = V1alpha1ResourceResult;
export const V1alpha1ResourceStatusSchema = V1alpha1ResourceStatus;
export const V1alpha1RetryStrategySchema = V1alpha1RetryStrategy;
export const V1alpha1RevisionHistorySchema = V1alpha1RevisionHistory;
export const V1alpha1RevisionMetadataSchema = V1alpha1RevisionMetadata;
export const V1alpha1SCMProviderGeneratorSchema = V1alpha1SCMProviderGenerator;
export const V1alpha1SCMProviderGeneratorAWSCodeCommitSchema = V1alpha1SCMProviderGeneratorAWSCodeCommit;
export const V1alpha1SCMProviderGeneratorAzureDevOpsSchema = V1alpha1SCMProviderGeneratorAzureDevOps;
export const V1alpha1SCMProviderGeneratorBitbucketSchema = V1alpha1SCMProviderGeneratorBitbucket;
export const V1alpha1SCMProviderGeneratorBitbucketServerSchema = V1alpha1SCMProviderGeneratorBitbucketServer;
export const V1alpha1SCMProviderGeneratorFilterSchema = V1alpha1SCMProviderGeneratorFilter;
export const V1alpha1SCMProviderGeneratorGiteaSchema = V1alpha1SCMProviderGeneratorGitea;
export const V1alpha1SCMProviderGeneratorGithubSchema = V1alpha1SCMProviderGeneratorGithub;
export const V1alpha1SCMProviderGeneratorGitlabSchema = V1alpha1SCMProviderGeneratorGitlab;
export const V1alpha1SecretRefSchema = V1alpha1SecretRef;
export const V1alpha1SignatureKeySchema = V1alpha1SignatureKey;
export const V1alpha1SyncOperationSchema = V1alpha1SyncOperation;
export const V1alpha1SyncOperationResourceSchema = V1alpha1SyncOperationResource;
export const V1alpha1SyncOperationResultSchema = V1alpha1SyncOperationResult;
export const V1alpha1SyncPolicySchema = V1alpha1SyncPolicy;
export const V1alpha1SyncPolicyAutomatedSchema = V1alpha1SyncPolicyAutomated;
export const V1alpha1SyncStatusSchema = V1alpha1SyncStatus;
export const V1alpha1SyncStrategySchema = V1alpha1SyncStrategy;
export const V1alpha1SyncStrategyApplySchema = V1alpha1SyncStrategyApply;
export const V1alpha1SyncStrategyHookSchema = V1alpha1SyncStrategyHook;
export const V1alpha1SyncWindowSchema = V1alpha1SyncWindow;
export const V1alpha1TLSClientConfigSchema = V1alpha1TLSClientConfig;
export const V1alpha1TagFilterSchema = V1alpha1TagFilter;
export const VersionVersionMessageSchema = VersionVersionMessage;
